include:
  - metadata/kafka.yaml
  - metadata/minio.yaml
  - metadata/mongo.yaml
  - metadata/postgres.yaml
  - metadata/redis.yaml

  - learning_platform_api_gateway/deployment/docker-compose.yaml
  - learning_platform_auth/deployment/docker-compose.yaml
  - learning_platform_users/deployment/docker-compose.yaml